[workspace]
authors = ["xavier <xavierabarr@gmail.com>"]
channels = ["conda-forge"]
name = "group_project"
platforms = ["linux-64", "win-64"]
version = "0.1.0"

[tasks]
exp = "python main.py --llm-model=Qwen/Qwen2.5-1.5B-Instruct --object-model=PekingU/rtdetr_r50vd --output-dir=data/detr_eval_videos --window-size=25"

yolo_exp = "python main.py --video-dir=data/traffic_light_detection --llm-model=Qwen/Qwen2.5-1.5B-Instruct --object-model=yolo --output-dir=traffic_light_eval --window-size=25"

combined_exp = "python main.py --llm-model=Qwen/Qwen2.5-1.5B-Instruct --object-model=combined --output-dir=data/combined_eval_videos --window-size=10"

combined_exp2 = "python main.py --video-dir=data/traffic_light_detection --visualize --llm-model=Qwen/Qwen2.5-1.5B-Instruct --object-model=combined --output-dir=data/combined_eval_videos_dataset2 --window-size=25"


test = "python main.py --visualize --llm-model=Qwen/Qwen2.5-1.5B-Instruct --object-model=PekingU/rtdetr_r50vd --max-videos=1"

yolo_test = "python main.py --video-dir=data/traffic_light_detection --visualize --llm-model=Qwen/Qwen2.5-1.5B-Instruct --object-model=yolo --max-videos=1 --output-dir=traffic_light_eval_test"

combined_test = "python examples/full_pipeline.py --video-path=data/reddit_dashcam_videos/video_40.mp4 --output-dir=pipeline_test --visualize --object-model=combined --llm-model=Qwen/Qwen2.5-1.5B-Instruct"


presentation_video_combined = "python examples/full_pipeline.py --video-path=data/traffic_light_detection/Video_Project_5.mp4 --output-dir=presentation_videos --visualize --object-model=combined --llm-model=Qwen/Qwen2.5-1.5B-Instruct --window-size=25"

presentation_video_t5 = "python examples/full_pipeline.py --video-path=data/traffic_light_detection/Video_Project_5.mp4 --output-dir=presentation_videos --visualize --object-model=combined --llm-model=google/flan-t5-small --window-size=10"

presentation_video_detr_only = "python examples/full_pipeline.py --video-path=data/traffic_light_detection/Video_Project_5.mp4 --output-dir=presentation_videos_detr_only --visualize --object-model=PekingU/rtdetr_r50vd --llm-model=Qwen/Qwen2.5-1.5B-Instruct"

presentation_final_video = "python examples/full_pipeline.py --video-path=data/reddit_dashcam_videos/video_28.mp4 --output-dir=presentation_videos --visualize --object-model=combined --llm-model=Qwen/Qwen2.5-1.5B-Instruct"


latency_t5_small = "python main.py --visualize --llm-model=google/flan-t5-small --object-model=combined --output-dir=data/latency_t5_small --window-size=10 --max-videos=1"

latency_t5_large = "python main.py --visualize --llm-model=google/flan-t5-large --object-model=combined --output-dir=data/latency_t5_large --window-size=10 --max-videos=1"

latency_deep_seek = "python main.py --visualize --llm-model=deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B --object-model=combined --output-dir=data/latency_deep_seek --window-size=10 --max-videos=1"

latency_phi = "python main.py --visualize --llm-model=microsoft/Phi-3.5-mini-instruct --object-model=combined --output-dir=data/latency_phi --window-size=10 --max-videos=1"

latency_qwen = "python main.py --visualize --llm-model=Qwen/Qwen2.5-1.5B-Instruct --object-model=combined --output-dir=data/latency_qwen --window-size=10 --max-videos=1"




[dependencies]
python = ">=3.14.4,<3.15"
pip = ">=26.0.1,<27"
transformers = ">=5.8.0,<6"


[pypi-dependencies]
torch = ">=2.11.0, <3"
torchvision = ">=0.26.0, <0.27"
matplotlib = ">=3.10.8, <4"
jupyterlab = ">=4.5.6, <5"
opencv-python = ">=4.13.0.92, <5"
transformers = ">=5.5.4, <6"
yt-dlp = ">=2026.3.17, <2027"
praw = ">=7.8.1, <8"
driving_assistant  = { path = ".", editable = true}
pytest = ">=9.0.3, <10"
accelerate = ">=1.13.0, <2"
bitsandbytes = ">=0.49.2, <0.50"
protobuf = ">=7.34.1, <8"
ultralytics = ">=8.4.45, <9"
