[workspace]
authors = ["xavier <xavierabarr@gmail.com>"]
channels = ["conda-forge"]
name = "group_project"
platforms = ["linux-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.4,<3.15"
pip = ">=26.0.1,<27"


[pypi-dependencies]
torch = ">=2.11.0, <3"
torchvision = ">=0.26.0, <0.27"
matplotlib = ">=3.10.8, <4"
jupyterlab = ">=4.5.6, <5"
opencv-python = ">=4.13.0.92, <5"
transformers = ">=5.5.4, <6"
yt-dlp = ">=2026.3.17, <2027"
praw = ">=7.8.1, <8"
driving_assistant  = { path = ".", editable = true}
pytest = ">=9.0.3, <10"
